#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=39
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=10
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spotify.sh"

sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

# Simple numeric labels for workspaces
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")

source "$ITEM_DIR/aerospace.sh"

for sid in $(aerospace list-workspaces --monitor focused --empty no); do
  # Determine icon based on workspace ID
  space_icon=""
  case "$sid" in
  1) space_icon="󰗀" ;;
  2) space_icon="󰖟" ;;
  3) space_icon="󰋋" ;;
  4) space_icon="󰎲" ;;
  5) space_icon="󰼓" ;;
  6) space_icon="󰎴" ;;
  7) space_icon="󰼕" ;;
  8) space_icon="󰎺" ;;
  9) space_icon="󰼗" ;;
  0) space_icon="󰗘" ;;
  *) space_icon="" ;;
  esac

  sketchybar --animate linear 20 \
      --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=$TRANSPARENT \
    background.corner_radius=5 \
    background.height=25 \
    background.drawing=off \
    background.padding_left=6 \
    background.padding_right=6 \
    y_offset=1 \
    icon="$space_icon" \
    icon.font="SF Pro:Bold:16.0" \
    icon.highlight_color=$ACCENT \
    label.drawing=off \
    label.font="sketchybar-app-font:Regular:14.0" \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Center

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
